server:
  port: 8080 # ??????

spring:
  datasource:
    # ??? lab_db ????????????? MySQL ???????
    url: jdbc:mysql://localhost:3306/lab_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root # ????????
    password: 20060315Aa # ???????
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis-Plus ????
mybatis-plus:
  configuration:
    # 1. ???? SQL ????????????????????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 2. ?????????? Java ?????????? username???????????
    map-underscore-to-camel-case: false
  # 3. ????????? .xml ???????????????
  mapper-locations: classpath:mapper/*.xml